import { createHash, randomUUID } from 'node:crypto';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

import type { ExportFormat } from '@/db/schema/tables';
import type { FastifyInstance } from 'fastify';

import { AppError } from '@/common/errors/app-error';
import { env } from '@/config/env';
import { parseDrawingId } from '@/domains/drawings/id';
import type { StartExportResponse } from '@/domains/exports/contracts';
import { formatExportId } from '@/domains/exports/id';
import { ExportsRepository } from '@/domains/exports/repository';
import { formatFileId } from '@/domains/files/id';

export class ExportsService {
  private readonly repository: ExportsRepository;

  public constructor(app: FastifyInstance) {
    this.repository = new ExportsRepository(app.db);
  }

  public async exportDrawing(input: {
    drawingId: string;
    format: ExportFormat;
  }): Promise<StartExportResponse> {
    const drawingNumericId = parseDrawingId(input.drawingId);
    const drawingExists = await this.repository.assertDrawingExists(drawingNumericId);
    if (!drawingExists) {
      throw new AppError('DRAWING_NOT_FOUND', 404, 'Drawing not found');
    }

    const exportsRoot = path.resolve(process.cwd(), env.STORAGE_EXPORTS_DIR);
    await mkdir(exportsRoot, { recursive: true });

    const extension = input.format === 'pdf' ? '.pdf' : '.png';
    const fileName = `${Date.now()}-${randomUUID()}${extension}`;
    const absolutePath = path.join(exportsRoot, fileName);
    const storagePath = path.posix.join(env.STORAGE_EXPORTS_DIR.replace(/\\/g, '/'), fileName);

    const buffer = this.buildPlaceholderExportBuffer({
      drawingId: input.drawingId,
      format: input.format,
    });
    await writeFile(absolutePath, buffer);

    const checksumSha256 = createHash('sha256').update(buffer).digest('hex');
    const mimeType = input.format === 'pdf' ? 'application/pdf' : 'image/png';

    const created = await this.repository.createExportArtifact({
      drawingId: drawingNumericId,
      format: input.format,
      storagePath,
      mimeType,
      originalName: `drawing-${input.drawingId}${extension}`,
      sizeBytes: buffer.byteLength,
      checksumSha256,
      status: 'completed',
    });

    return {
      exportId: formatExportId(created.exportId),
      drawingId: input.drawingId,
      format: input.format,
      status: 'completed',
      fileId: formatFileId(created.fileId),
      storagePath,
    };
  }

  private buildPlaceholderExportBuffer(input: { drawingId: string; format: ExportFormat }): Buffer {
    if (input.format === 'pdf') {
      const content = [
        '%PDF-1.4',
        '% Placeholder export generated by backend stage-5 scaffold',
        `1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj`,
        `2 0 obj<</Type/Pages/Count 1/Kids[3 0 R]>>endobj`,
        `3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 300 120]/Contents 4 0 R>>endobj`,
        `4 0 obj<</Length 68>>stream`,
        `BT /F1 12 Tf 20 80 Td (Drawing ${input.drawingId} placeholder export) Tj ET`,
        `endstream endobj`,
        'xref',
        '0 5',
        '0000000000 65535 f ',
        'trailer<</Size 5/Root 1 0 R>>',
        'startxref',
        '0',
        '%%EOF',
      ].join('\n');
      return Buffer.from(content, 'utf8');
    }

    const onePixelPngBase64 =
      'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9WQyQJ0AAAAASUVORK5CYII=';
    return Buffer.from(onePixelPngBase64, 'base64');
  }
}
